site_name: Capacitações DCCG
site_url: https://gabrieladsribeiro.github.io/repo01/

# Configuration
theme:
  name: material
  theme:
  palette:
    primary: teal
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - blog
  - search

nav:
  - Início: index.md
  - Legislação: legislacao.md
  - Documentos: documentos.md
  - Blog: blog/index.md
  

